[build-system]
requires = [
    # Essentials
    "setuptools >= 34.4",

    # Plugins
    "setuptools_scm[toml] >= 3.5",
    "setuptools_scm_git_archive >= 1.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
